### ISSUE TITLE
GB rail

### ISSUE THREAD

**Issue by linusnorton** [public-transport/european-transport-operators#10]
Unofficial GB rail can found: https://planar.network/projects/feeds

**Comment by juliuste** [comment]
Thank you very much! Do you mind opening a PR to add the info? (If not, also not a problem, I will do it then)

**Comment by linusnorton** [comment]
I've opened a PR: https://github.com/public-transport/european-transport-operators/pull/11

I also added the national coach service and a very, very unofficial Eurostar feed.

**Comment by juliuste** [comment]
Will close this issue since the PR was merged, re-open if I missed something. And again: Thank you very much for the contribution! 🙃
