### ISSUE TITLE
add more than static data to the list

### ISSUE THREAD

**Issue by derhuerst** [public-transport/european-transport-operators#3]
For example, adding the [official Dutch Railways API](https://www.ns.nl/en/travel-information/ns-api) would be useful.

**Comment by vanderwees** [comment]
Two more useful links:

- Basic information on open data and historic datasets on request: https://www.rijdendetreinen.nl/over/open-data
- An effort to deliver realtime open data info: https://ndovloket.nl/ (seems related to/the follow-up of the openov.nl effort)
