### ISSUE TITLE
Croatian Railroads (HŽPP) provides GTFS data

### ISSUE THREAD

**Issue by JCGoran** [public-transport/european-transport-operators#9]
To my surprise, it seems that Croatian Railroads (HŽPP) does have a GTFS-format dataset available at http://www.hzpp.hr/Media/Default/GTFS/GTFS_files.zip.
The [source](https://www.europeandataportal.eu/data/en/dataset/vozni-red-h-putni-kog-prijevoza-u-gtfs-obliku) ([and the original](https://data.gov.hr/dataset/vozni-red-h-putni-kog-prijevoza-u-gtfs-obliku)) claim that the data is refreshed daily at 01:00.

**Comment by juliuste** [comment]
Sorry for addressing this so late, thank you very much for the hint, I added a link to the dataset.
